name: Release zip on tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make zip
        run: |
          bash tools/pack.sh
        shell: bash

      - name: Upload zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: dist/*.zip

  create-release:
    needs: build-zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: extension-zip
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
